//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswerBool
    {
        public int Id { get; set; }
        public bool Answer { get; set; }
        public int BoolId { get; set; }
        public int UserSessionId { get; set; }
    
        public virtual BoolTrue BoolTrue { get; set; }
        public virtual UserToSession UserToSession { get; set; }
    }
}
